from typing import TypedDict, List, Dict, Optional, Any

class ResumeTailorState(TypedDict):
    resume_data: Dict[str, Any]  # The structured resume input
    job_description: str         # The text of the job description
    analysis: Dict[str, Any]     # Results from analyzing the JD (keywords, culture, etc.)
    company_research: str        # Context found about the company
    tailoring_strategy: str      # The plan generated by the agent
    tailored_resume_data: Dict[str, Any] # The final structured resume
    config: Dict[str, Any]       # Configuration (remove_irrelevant, exaggerate, etc.)
